Features
deniodev/Hello-Microverse pull request #1
Opened 2023-03-22 18:28 UTC by deniodev

Test

2023-03-22 19:51 UTC, souad988 requested changes
Hi @deniodev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/227019151-463095e0-ae96-44d1-b659-5a8738e990fd.gif)


## Highlights
✔No linter errors 
✔Great efforts

## Required Changes ♻️
_Check the comments under the review._
_ Also consider adding a valid licence file and update the link to it in your README this is required for legal reasons
_also put your README file in this branch as I can not give feedback about it now  and always do all the work from your feature branch submit for review and only when approved that you can move your code to the main branch 
_ Kindly change this PR title and summary to something that describes better the work done in this feature  otherwise this title is misleading and it doesn't give any idea about the work and the feature.
_Last thing is Please make all these changes in this same branch and submit for review .
_ you have done great keep up the hard work 💪💪💪
 
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 19:51 UTC, souad988 commented on index.html
> +</body>
Kindly add a h1 title to your page as requested in the requirements

2023-03-22 19:51 UTC, souad988 commented on index.html
> +    <title>Document</title>
Please add a valid title to your page referring to your project exp: Hello Microverse

2023-03-23 09:37 UTC, adel-gu approved these changes
# Status: Approved 🟢 

Hi @deniodev 👋🏼 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- You added the H1 heading ✔️ 
- The app has a meaningful title now ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 09:37 UTC, adel-gu commented on .github/workflows/linters.yml
> +
- [OPTIONAL] In future projects consider giving your branch meaningful naming that conveys an action or a feature that you are trying to implement 💪🏼 

eg:
1. `hello-microvers`
2.  `setup-hello-microverse`

2023-03-23 09:45 UTC, deniodev commented on .github/workflows/linters.yml
> +
Thank you for your time.

2023-03-23 10:03 UTC, merged